export interface Country {
  code: string;      // ISO 2-letter
  name: string;      // O'zbekcha nomi
  dial: string;      // +998
  flag: string;      // emoji
}

// O'zbekiston va qo'shnilar birinchi
export const COUNTRIES: Country[] = [
  // ═══════════ Markaziy Osiyo ═══════════
  { code: "UZ", name: "O'zbekiston", dial: "+998", flag: "🇺🇿" },
  { code: "KZ", name: "Qozog'iston", dial: "+7", flag: "🇰🇿" },
  { code: "KG", name: "Qirg'iziston", dial: "+996", flag: "🇰🇬" },
  { code: "TJ", name: "Tojikiston", dial: "+992", flag: "🇹🇯" },
  { code: "TM", name: "Turkmaniston", dial: "+993", flag: "🇹🇲" },
  { code: "AF", name: "Afg'oniston", dial: "+93", flag: "🇦🇫" },

  // ═══════════ MDH / Mustaqil davlatlar ═══════════
  { code: "RU", name: "Rossiya", dial: "+7", flag: "🇷🇺" },
  { code: "AZ", name: "Ozarbayjon", dial: "+994", flag: "🇦🇿" },
  { code: "AM", name: "Armaniston", dial: "+374", flag: "🇦🇲" },
  { code: "GE", name: "Gruziya", dial: "+995", flag: "🇬🇪" },
  { code: "BY", name: "Belarus", dial: "+375", flag: "🇧🇾" },
  { code: "UA", name: "Ukraina", dial: "+380", flag: "🇺🇦" },
  { code: "MD", name: "Moldova", dial: "+373", flag: "🇲🇩" },

  // ═══════════ Turkiy davlatlar ═══════════
  { code: "TR", name: "Turkiya", dial: "+90", flag: "🇹🇷" },

  // ═══════════ Yaqin Sharq ═══════════
  { code: "AE", name: "BAA", dial: "+971", flag: "🇦🇪" },
  { code: "SA", name: "Saudiya Arabistoni", dial: "+966", flag: "🇸🇦" },
  { code: "QA", name: "Qatar", dial: "+974", flag: "🇶🇦" },
  { code: "KW", name: "Quvayt", dial: "+965", flag: "🇰🇼" },
  { code: "BH", name: "Bahrayn", dial: "+973", flag: "🇧🇭" },
  { code: "OM", name: "Ummon", dial: "+968", flag: "🇴🇲" },
  { code: "JO", name: "Iordaniya", dial: "+962", flag: "🇯🇴" },
  { code: "LB", name: "Livan", dial: "+961", flag: "🇱🇧" },
  { code: "SY", name: "Suriya", dial: "+963", flag: "🇸🇾" },
  { code: "IQ", name: "Iroq", dial: "+964", flag: "🇮🇶" },
  { code: "IR", name: "Eron", dial: "+98", flag: "🇮🇷" },
  { code: "IL", name: "Isroil", dial: "+972", flag: "🇮🇱" },
  { code: "YE", name: "Yaman", dial: "+967", flag: "🇾🇪" },

  // ═══════════ Osiyo ═══════════
  { code: "CN", name: "Xitoy", dial: "+86", flag: "🇨🇳" },
  { code: "HK", name: "Gonkong", dial: "+852", flag: "🇭🇰" },
  { code: "JP", name: "Yaponiya", dial: "+81", flag: "🇯🇵" },
  { code: "KR", name: "Janubiy Koreya", dial: "+82", flag: "🇰🇷" },
  { code: "KP", name: "Shimoliy Koreya", dial: "+850", flag: "🇰🇵" },
  { code: "IN", name: "Hindiston", dial: "+91", flag: "🇮🇳" },
  { code: "PK", name: "Pokiston", dial: "+92", flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh", dial: "+880", flag: "🇧🇩" },
  { code: "NP", name: "Nepal", dial: "+977", flag: "🇳🇵" },
  { code: "LK", name: "Shri-Lanka", dial: "+94", flag: "🇱🇰" },
  { code: "MV", name: "Maldiv orollari", dial: "+960", flag: "🇲🇻" },
  { code: "BT", name: "Butan", dial: "+975", flag: "🇧🇹" },
  { code: "MM", name: "Myanma", dial: "+95", flag: "🇲🇲" },
  { code: "TH", name: "Tailand", dial: "+66", flag: "🇹🇭" },
  { code: "VN", name: "Vyetnam", dial: "+84", flag: "🇻🇳" },
  { code: "LA", name: "Laos", dial: "+856", flag: "🇱🇦" },
  { code: "KH", name: "Kambodja", dial: "+855", flag: "🇰🇭" },
  { code: "MY", name: "Malayziya", dial: "+60", flag: "🇲🇾" },
  { code: "SG", name: "Singapur", dial: "+65", flag: "🇸🇬" },
  { code: "ID", name: "Indoneziya", dial: "+62", flag: "🇮🇩" },
  { code: "PH", name: "Filippin", dial: "+63", flag: "🇵🇭" },
  { code: "BN", name: "Bruney", dial: "+673", flag: "🇧🇳" },
  { code: "TL", name: "Sharqiy Timor", dial: "+670", flag: "🇹🇱" },
  { code: "MN", name: "Mongoliya", dial: "+976", flag: "🇲🇳" },

  // ═══════════ Yevropa ═══════════
  { code: "DE", name: "Germaniya", dial: "+49", flag: "🇩🇪" },
  { code: "FR", name: "Fransiya", dial: "+33", flag: "🇫🇷" },
  { code: "GB", name: "Buyuk Britaniya", dial: "+44", flag: "🇬🇧" },
  { code: "IE", name: "Irlandiya", dial: "+353", flag: "🇮🇪" },
  { code: "IT", name: "Italiya", dial: "+39", flag: "🇮🇹" },
  { code: "ES", name: "Ispaniya", dial: "+34", flag: "🇪🇸" },
  { code: "PT", name: "Portugaliya", dial: "+351", flag: "🇵🇹" },
  { code: "NL", name: "Niderlandiya", dial: "+31", flag: "🇳🇱" },
  { code: "BE", name: "Belgiya", dial: "+32", flag: "🇧🇪" },
  { code: "LU", name: "Lyuksemburg", dial: "+352", flag: "🇱🇺" },
  { code: "CH", name: "Shveysariya", dial: "+41", flag: "🇨🇭" },
  { code: "AT", name: "Avstriya", dial: "+43", flag: "🇦🇹" },
  { code: "SE", name: "Shvetsiya", dial: "+46", flag: "🇸🇪" },
  { code: "NO", name: "Norvegiya", dial: "+47", flag: "🇳🇴" },
  { code: "DK", name: "Daniya", dial: "+45", flag: "🇩🇰" },
  { code: "FI", name: "Finlyandiya", dial: "+358", flag: "🇫🇮" },
  { code: "IS", name: "Islandiya", dial: "+354", flag: "🇮🇸" },
  { code: "PL", name: "Polsha", dial: "+48", flag: "🇵🇱" },
  { code: "CZ", name: "Chexiya", dial: "+420", flag: "🇨🇿" },
  { code: "SK", name: "Slovakiya", dial: "+421", flag: "🇸🇰" },
  { code: "HU", name: "Vengriya", dial: "+36", flag: "🇭🇺" },
  { code: "RO", name: "Ruminiya", dial: "+40", flag: "🇷🇴" },
  { code: "BG", name: "Bolgariya", dial: "+359", flag: "🇧🇬" },
  { code: "GR", name: "Gretsiya", dial: "+30", flag: "🇬🇷" },
  { code: "HR", name: "Xorvatiya", dial: "+385", flag: "🇭🇷" },
  { code: "SI", name: "Sloveniya", dial: "+386", flag: "🇸🇮" },
  { code: "RS", name: "Serbiya", dial: "+381", flag: "🇷🇸" },
  { code: "BA", name: "Bosniya va Gertsegovina", dial: "+387", flag: "🇧🇦" },
  { code: "ME", name: "Chernogoriya", dial: "+382", flag: "🇲🇪" },
  { code: "MK", name: "Shimoliy Makedoniya", dial: "+389", flag: "🇲🇰" },
  { code: "AL", name: "Albaniya", dial: "+355", flag: "🇦🇱" },
  { code: "XK", name: "Kosovo", dial: "+383", flag: "🇽🇰" },
  { code: "CY", name: "Kipr", dial: "+357", flag: "🇨🇾" },
  { code: "MT", name: "Malta", dial: "+356", flag: "🇲🇹" },
  { code: "EE", name: "Estoniya", dial: "+372", flag: "🇪🇪" },
  { code: "LV", name: "Latviya", dial: "+371", flag: "🇱🇻" },
  { code: "LT", name: "Litva", dial: "+370", flag: "🇱🇹" },
  { code: "MC", name: "Monako", dial: "+377", flag: "🇲🇨" },
  { code: "AD", name: "Andorra", dial: "+376", flag: "🇦🇩" },
  { code: "LI", name: "Lixtenshteyn", dial: "+423", flag: "🇱🇮" },
  { code: "SM", name: "San-Marino", dial: "+378", flag: "🇸🇲" },
  { code: "VA", name: "Vatikan", dial: "+379", flag: "🇻🇦" },

  // ═══════════ Afrika ═══════════
  { code: "EG", name: "Misr", dial: "+20", flag: "🇪🇬" },
  { code: "LY", name: "Liviya", dial: "+218", flag: "🇱🇾" },
  { code: "TN", name: "Tunis", dial: "+216", flag: "🇹🇳" },
  { code: "DZ", name: "Jazoir", dial: "+213", flag: "🇩🇿" },
  { code: "MA", name: "Marokash", dial: "+212", flag: "🇲🇦" },
  { code: "SD", name: "Sudan", dial: "+249", flag: "🇸🇩" },
  { code: "SS", name: "Janubiy Sudan", dial: "+211", flag: "🇸🇸" },
  { code: "ET", name: "Efiopiya", dial: "+251", flag: "🇪🇹" },
  { code: "ER", name: "Eritreya", dial: "+291", flag: "🇪🇷" },
  { code: "SO", name: "Somali", dial: "+252", flag: "🇸🇴" },
  { code: "DJ", name: "Jibuti", dial: "+253", flag: "🇩🇯" },
  { code: "KE", name: "Keniya", dial: "+254", flag: "🇰🇪" },
  { code: "TZ", name: "Tanzaniya", dial: "+255", flag: "🇹🇿" },
  { code: "UG", name: "Uganda", dial: "+256", flag: "🇺🇬" },
  { code: "RW", name: "Ruanda", dial: "+250", flag: "🇷🇼" },
  { code: "BI", name: "Burundi", dial: "+257", flag: "🇧🇮" },
  { code: "NG", name: "Nigeriya", dial: "+234", flag: "🇳🇬" },
  { code: "GH", name: "Gana", dial: "+233", flag: "🇬🇭" },
  { code: "CI", name: "Kot-d'Ivuar", dial: "+225", flag: "🇨🇮" },
  { code: "SN", name: "Senegal", dial: "+221", flag: "🇸🇳" },
  { code: "ML", name: "Mali", dial: "+223", flag: "🇲🇱" },
  { code: "BF", name: "Burkina-Faso", dial: "+226", flag: "🇧🇫" },
  { code: "NE", name: "Niger", dial: "+227", flag: "🇳🇪" },
  { code: "TG", name: "Togo", dial: "+228", flag: "🇹🇬" },
  { code: "BJ", name: "Benin", dial: "+229", flag: "🇧🇯" },
  { code: "MR", name: "Mavritaniya", dial: "+222", flag: "🇲🇷" },
  { code: "GM", name: "Gambiya", dial: "+220", flag: "🇬🇲" },
  { code: "GW", name: "Gvineya-Bisau", dial: "+245", flag: "🇬🇼" },
  { code: "GN", name: "Gvineya", dial: "+224", flag: "🇬🇳" },
  { code: "SL", name: "Syerra-Leone", dial: "+232", flag: "🇸🇱" },
  { code: "LR", name: "Liberiya", dial: "+231", flag: "🇱🇷" },
  { code: "CM", name: "Kamerun", dial: "+237", flag: "🇨🇲" },
  { code: "CF", name: "Markaziy Afrika Respublikasi", dial: "+236", flag: "🇨🇫" },
  { code: "TD", name: "Chad", dial: "+235", flag: "🇹🇩" },
  { code: "CG", name: "Kongo", dial: "+242", flag: "🇨🇬" },
  { code: "CD", name: "Kongo Demokratik Respublikasi", dial: "+243", flag: "🇨🇩" },
  { code: "GA", name: "Gabon", dial: "+241", flag: "🇬🇦" },
  { code: "GQ", name: "Ekvatorial Gvineya", dial: "+240", flag: "🇬🇶" },
  { code: "AO", name: "Angola", dial: "+244", flag: "🇦🇴" },
  { code: "ZM", name: "Zambiya", dial: "+260", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabve", dial: "+263", flag: "🇿🇼" },
  { code: "MW", name: "Malavi", dial: "+265", flag: "🇲🇼" },
  { code: "MZ", name: "Mozambik", dial: "+258", flag: "🇲🇿" },
  { code: "MG", name: "Madagaskar", dial: "+261", flag: "🇲🇬" },
  { code: "MU", name: "Mavrikiy", dial: "+230", flag: "🇲🇺" },
  { code: "SC", name: "Seyshel orollari", dial: "+248", flag: "🇸🇨" },
  { code: "KM", name: "Komor orollari", dial: "+269", flag: "🇰🇲" },
  { code: "ZA", name: "Janubiy Afrika", dial: "+27", flag: "🇿🇦" },
  { code: "LS", name: "Lesoto", dial: "+266", flag: "🇱🇸" },
  { code: "SZ", name: "Esvatini", dial: "+268", flag: "🇸🇿" },
  { code: "NA", name: "Namibiya", dial: "+264", flag: "🇳🇦" },
  { code: "BW", name: "Botsvana", dial: "+267", flag: "🇧🇼" },
  { code: "CV", name: "Kabo-Verde", dial: "+238", flag: "🇨🇻" },
  { code: "ST", name: "San-Tome va Prinsipi", dial: "+239", flag: "🇸🇹" },

  // ═══════════ Amerika ═══════════
  { code: "US", name: "AQSH", dial: "+1", flag: "🇺🇸" },
  { code: "CA", name: "Kanada", dial: "+1", flag: "🇨🇦" },
  { code: "MX", name: "Meksika", dial: "+52", flag: "🇲🇽" },
  { code: "GT", name: "Gvatemala", dial: "+502", flag: "🇬🇹" },
  { code: "BZ", name: "Beliz", dial: "+501", flag: "🇧🇿" },
  { code: "SV", name: "Salvador", dial: "+503", flag: "🇸🇻" },
  { code: "HN", name: "Gonduras", dial: "+504", flag: "🇭🇳" },
  { code: "NI", name: "Nikaragua", dial: "+505", flag: "🇳🇮" },
  { code: "CR", name: "Kosta-Rika", dial: "+506", flag: "🇨🇷" },
  { code: "PA", name: "Panama", dial: "+507", flag: "🇵🇦" },
  { code: "CU", name: "Kuba", dial: "+53", flag: "🇨🇺" },
  { code: "JM", name: "Yamayka", dial: "+1876", flag: "🇯🇲" },
  { code: "HT", name: "Gaiti", dial: "+509", flag: "🇭🇹" },
  { code: "DO", name: "Dominikan Respublikasi", dial: "+1809", flag: "🇩🇴" },
  { code: "PR", name: "Puerto-Riko", dial: "+1787", flag: "🇵🇷" },
  { code: "TT", name: "Trinidad va Tobago", dial: "+1868", flag: "🇹🇹" },
  { code: "BB", name: "Barbados", dial: "+1246", flag: "🇧🇧" },
  { code: "BS", name: "Bagama orollari", dial: "+1242", flag: "🇧🇸" },
  { code: "CO", name: "Kolumbiya", dial: "+57", flag: "🇨🇴" },
  { code: "VE", name: "Venesuela", dial: "+58", flag: "🇻🇪" },
  { code: "GY", name: "Gayana", dial: "+592", flag: "🇬🇾" },
  { code: "SR", name: "Surinam", dial: "+597", flag: "🇸🇷" },
  { code: "EC", name: "Ekvador", dial: "+593", flag: "🇪🇨" },
  { code: "PE", name: "Peru", dial: "+51", flag: "🇵🇪" },
  { code: "BR", name: "Braziliya", dial: "+55", flag: "🇧🇷" },
  { code: "BO", name: "Boliviya", dial: "+591", flag: "🇧🇴" },
  { code: "PY", name: "Paragvay", dial: "+595", flag: "🇵🇾" },
  { code: "UY", name: "Urugvay", dial: "+598", flag: "🇺🇾" },
  { code: "AR", name: "Argentina", dial: "+54", flag: "🇦🇷" },
  { code: "CL", name: "Chili", dial: "+56", flag: "🇨🇱" },

  // ═══════════ Okeaniya ═══════════
  { code: "AU", name: "Avstraliya", dial: "+61", flag: "🇦🇺" },
  { code: "NZ", name: "Yangi Zelandiya", dial: "+64", flag: "🇳🇿" },
  { code: "FJ", name: "Fiji", dial: "+679", flag: "🇫🇯" },
  { code: "PG", name: "Papua-Yangi Gvineya", dial: "+675", flag: "🇵🇬" },
  { code: "SB", name: "Solomon orollari", dial: "+677", flag: "🇸🇧" },
  { code: "VU", name: "Vanuatu", dial: "+678", flag: "🇻🇺" },
  { code: "WS", name: "Samoa", dial: "+685", flag: "🇼🇸" },
  { code: "TO", name: "Tonga", dial: "+676", flag: "🇹🇴" },
  { code: "KI", name: "Kiribati", dial: "+686", flag: "🇰🇮" },
  { code: "NR", name: "Nauru", dial: "+674", flag: "🇳🇷" },
  { code: "TV", name: "Tuvalu", dial: "+688", flag: "🇹🇻" },
  { code: "PW", name: "Palau", dial: "+680", flag: "🇵🇼" },
  { code: "FM", name: "Mikroneziya", dial: "+691", flag: "🇫🇲" },
  { code: "MH", name: "Marshall orollari", dial: "+692", flag: "🇲🇭" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // O'zbekiston
